---

- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: install kevin npm applications
      npm: name={{item}} state=latest global=yes
      with_items:
        - autoprefixer
        - bower
        - express
        - grunt
        - gulp
        - grunt-cli
        - generator-angular
        - generator-cordova
        - generator-express-react
        - generator-reactjs
        - generator-node
        - generator-react-webpack
        - jasmine-node
        - karma
        - mocha
        - ngrok
        - ios-sim
        - phantomjs
        - protractor
        - readable-stream
        - yo
    - name: install kevin apt-get applications
      apt: name={{item}} state=latest
      sudo: yes
      with_items:
        - ant
        - arping
        - autoconf
        - automake
        - cmake
        - coreutils
        - findutils
        - fontconfig
        - fping
        - gawk
        - git
        - git-extras
        - git-flow
        - gmp
        - gnutls
        - gtk+
        - gtksourceview
        - htop
        - hub
        - jmeter
        - jpeg
        - lame
        - leiningen
        - lftp
        - lua
        - lzip
        - mad
        - memcached
        - mercurial
        - mongodb
        - mutt
        - nettle
        - nginx-full
        - node
        - openssl
        - ossp-uuid
        - pango
        - pbzip2
        - postgresql
        - pstree
        - pv
        - redis
        - sbt
        - scala
        - selenium-server-standalone
        - shmux
        - sox
        - sqlite
        - tmux
        - watch
        - wget
        - zeromq

  vars:
    - computername: art3mis
    - git_user_name: Kevin Krauss
    - git_user_email: earlkrauss@gmail.com
    - sublime_packages:
        - dest: "Alignment"
          repo: "https://github.com/wbond/sublime_alignment.git"
          version: "master"
        - dest: "BeautifyRuby"
          repo: "https://github.com/CraigWilliams/BeautifyRuby.git"
          version: "master"
        - dest: "Emmet"
          repo: "https://github.com/sergeche/emmet-sublime.git"
          version: "master"
        - dest: "Git"
          repo: "https://github.com/kemayo/sublime-text-git.git"
          version: "master"
        - dest: "Tomorrow Color Schemes"
          repo: "https://github.com/theymaybecoders/sublime-tomorrow-theme.git"
          version: "master"
        - dest: "ReactJS"
          repo: "https://github.com/reactjs/sublime-react.git"
          version: "master"
        - dest: "HTMLPrettify"
          repo: "https://github.com/victorporof/Sublime-HTMLPrettify.git"
          version: "master"
        - dest: "SideBarEnhancements"
          repo: "https://github.com/titoBouzout/SideBarEnhancements"
          version: "st3"
        - dest: "GitGutter"
          repo: "https://github.com/jisaacks/GitGutter.git"
          version: "master"
        - dest: "BracketHighlighter"
          repo: "https://github.com/facelessuser/BracketHighlighter.git"
          version: "master"
        - dest: "Theme - Soda"
          repo: "https://github.com/buymeasoda/soda-theme.git"
          version: "master"
        - dest: "Base16"
          repo: "https://github.com/chriskempson/base16-textmate.git"
          version: "master"
        - dest: "ApplySyntax"
          repo: "https://github.com/facelessuser/ApplySyntax.git"
          version: "master"
        - dest: "SublimeAllAutocomplete"
          repo: "https://github.com/alienhard/SublimeAllAutocomplete"
          version: "master"
        - dest: "Ansible"
          repo: "https://github.com/clifford-github/sublime-ansible.git"
          version: "master"
    - sublime_text_color_scheme: "Packages/Tomorrow Color Schemes/Tomorrow.tmTheme"
    - sublime_text_theme: "Soda Light.sublime-theme"
