---
# tasks file for ansible-role-postgresql

- name: increase shared memory allocation size
  become: yes
  sysctl: name=kern.sysv.shmall value=131072000 state=present reload=no sysctl_set=yes

- name: increase shared memory max
  become: yes
  sysctl: name=kern.sysv.shmmax value=524288000 state=present reload=no sysctl_set=yes

- name: install postgresql
  homebrew: name=postgresql state=latest

- name: install psycopg2
  become: yes
  pip: name=psycopg2

- name: blow away default image's data directory
  shell: rm -Rf /usr/local/var/postgres;
  args:
    creates: /usr/local/var/postgres/postgres-dbinit.done

- name: create the database
  shell: /usr/local/bin/initdb -U postgres -A trust --encoding=utf8 --locale=en_US /usr/local/var/postgres; touch /usr/local/var/postgres/postgres-dbinit.done;
  args:
    creates: /usr/local/var/postgres/postgres-dbinit.done

- name: manage postgres directories
  become: yes
  file:
    path: "{{item}}"
    state: directory
    mode: 0700
  with_items:
    - /usr/local/var/postgres/

- name: install launchagents
  file: src=/usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist path=~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist state=link force=yes

- name: check if postgresql is loaded
  shell: launchctl list
  changed_when: False
  register: postgresql_loaded_result

- name: launch postgresql
  shell: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
  when: "'homebrew.mxcl.postgresql' not in postgresql_loaded_result.stdout"

- pause: seconds=5
